[package]
name = "rust-headless-cms"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = "0.5.0-rc.2"
surrealdb = "1.0.0-beta.7"
serde = "1.0.133"